# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QPhenometrics
                                 A QGIS plugin
 QPhenometrics
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-03-27
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Sofia Sinoti
        email                : a
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.core import QgsProject, QgsVectorLayer
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction,QPushButton, QLabel, QFileDialog
from qgis import processing
from qgis.utils import iface
from qgis.core import *
from processing.core.Processing import Processing

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .QPhenometrics_dialog import QPhenometricsDialog
import os.path
import datetime
import matplotlib.pyplot as plt
import scipy as sp
from scipy.interpolate import CubicSpline
from scipy.signal import savgol_filter
import numpy as np
import tempfile
import statistics


class QPhenometrics:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """/Users/sofiasinoti/Downloads/GDAL-3.4.3-cp38-cp38-win_amd64.whlConstructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'QPhenometrics_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&QPhenometrics')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('QPhenometrics', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/QPhenometrics/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'QPhenometrics'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&QPhenometrics'),
                action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = QPhenometricsDialog()
            self.dlg.pbStart.clicked.connect(self.conclude)
            self.dlg.pbsearchpath.clicked.connect(self.selectfolderpath)
            self.dlg.pbselectshp.clicked.connect(self.selectshppath)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed

    def conclude(self):
        ## NDVI ROOT AND NDVI DATES


        ## DATA PATH IF AT FOLDER
        B04 = []
        B08 = []
        NDVIdate = []

        for root, dirs, files in os.walk(str(self.pathtofolder)):
            for f in files:
                found4 = f.find('B04')
                found8 = f.find('B08')
                if found4 > -1:
                    pathb04 = root + '//' + f
                    print(pathb04)
                    print(f[8:12], (f[12:14]), f[14:16])

                    datendvi = datetime.datetime(int(f[7:11]), int(f[11:13]), int(f[13:15]))
                    NDVIdate.append(datendvi)
                    B04.append(pathb04)

                if found8 > -1:
                    pathb08 = root + '//' + f
                    B08.append(pathb08)
        B04.sort()
        B08.sort()
        NDVIdate.sort()


        ##NDVI VALUES
        NDVIvalue = []
        for itemndvi in range(len(B04)):
        #CUT LAYERS
            Processing.initialize()
            vl = QgsVectorLayer(str(self.pathtoshp), 'poligon', 'org')

            REDcutlayer = processing.run("gdal:cliprasterbymasklayer", {'INPUT': B04[itemndvi],
                                                                         'MASK': self.pathtoshp,
                                                                         'SOURCE_CRS': None,
                                                                         'TARGET_CRS': None,
                                                                         'TARGET_EXTENT': None,
                                                                         'NODATA': None,
                                                                         'ALPHA_BAND': False,
                                                                         'CROP_TO_CUTLINE': True,
                                                                         'KEEP_RESOLUTION': False,
                                                                         'SET_RESOLUTION': False,
                                                                         'X_RESOLUTION': None,
                                                                         'Y_RESOLUTION': None,
                                                                         'MULTITHREADING': False,
                                                                         'OPTIONS': '',
                                                                         'DATA_TYPE': 0,
                                                                         'EXTRA': '',
                                                                         'OUTPUT': QgsProcessingUtils.generateTempFilename(
                                                                             'REDlayer.tif')})

            REDpath = REDcutlayer['OUTPUT']

            NIRcutlayer = processing.run("gdal:cliprasterbymasklayer", {'INPUT': B08[itemndvi],
                                                                         'MASK': self.pathtoshp,
                                                                         'SOURCE_CRS': None,
                                                                         'TARGET_CRS': None,
                                                                         'TARGET_EXTENT': None,
                                                                         'NODATA': None,
                                                                         'ALPHA_BAND': False,
                                                                         'CROP_TO_CUTLINE': True,
                                                                         'KEEP_RESOLUTION': False,
                                                                         'SET_RESOLUTION': False,
                                                                         'X_RESOLUTION': None,
                                                                         'Y_RESOLUTION': None,
                                                                         'MULTITHREADING': False,
                                                                         'OPTIONS': '',
                                                                         'DATA_TYPE': 0,
                                                                         'EXTRA': '',
                                                                         'OUTPUT': QgsProcessingUtils.generateTempFilename(
                                                                             'NIRlayer.tif')})

            NIRpath = NIRcutlayer['OUTPUT']

            iface.addRasterLayer(REDpath, "red")
            iface.addRasterLayer(NIRpath, "nir")
            ##NDVI CALCULATION

            NDVIitem = processing.run("qgis:rastercalculator", {'CELLSIZE': 0,
                                                                'EXPRESSION': ' ( "nir@1" - "red@1" ) / ( "nir@1" + "red@1" ) ',
                                                                'LAYERS': [
                                                                    REDpath,
                                                                    NIRpath],
                                                                'EXTENT': None,
                                                                'OUTPUT': QgsProcessingUtils.generateTempFilename('NDVIlayer.tif')})

            NDVIpath = NDVIitem['OUTPUT']

            iface.addRasterLayer(str(NDVIpath), "ndvi")

            ## EXTRACT MEAN VALUE:
            NDVIestpath = tempfile.NamedTemporaryFile()
            NDVIest = processing.run("native:rasterlayerstatistics",
                                     {'INPUT': str(NDVIpath),
                                      'BAND': 1,
                                      'OUTPUT_HTML_FILE': NDVIestpath.name})

            with open(NDVIestpath.name, 'r', encoding='utf-8') as ndviest1:
                ndviest = ndviest1.read()
                listitemest = ndviest.splitlines()
                startndviitem = 0
                ndvivalueitem = ''
                for item in listitemest[6]:
                    if item.isnumeric():
                        startndviitem = startndviitem + 1
                    if startndviitem >= 1 and startndviitem < 15:
                        ndvivalueitem = ndvivalueitem + item
                ndvivalueitem.replace("</p>", "")
                ndvivalueitem.replace(" ", "")
                NDVIvalue.append(float(ndvivalueitem))

            QgsProject.instance().removeAllMapLayers()

        ## NDVI PLOT GRAPHICS
        # DATE ORGANIZE TO SPLINE
        DATA = []  # date as number
        DATA2 = []  # date as array str
        for i in NDVIdate:
            item = i.strftime("%Y%m%d")
            item2 = i.strftime("%d/%m/%Y")
            DATA.append(int(item))
            DATA2.append(item2)
        DATA2 = np.array(DATA2)



        # GRAPHIC PLOT


        fig, ax = plt.subplots(figsize=(10, 2 + 6 / 2.5))

        #AXES VALUES
        # DEFINE X VALUES BY DAY DIFFERENCE
        x_values = []
        for date in range(len(NDVIdate)):
            if date == 0:
                x_values.append(0)
            else:
                delta = NDVIdate[date] - NDVIdate[0]
                x_values.append(delta.days)

        y_values = NDVIvalue


        x_new = x_values


        # Savotsky Golay

        ySavGol = savgol_filter(y_values, 5, 3)

        # Spline

        f = CubicSpline(x_values, y_values, bc_type='natural')
        ySpline = f(x_new)

        # DMA5 method

        yDMA5 = []
        for i in range(len(y_values)):
            if i >= 4:
                y_value = (y_values[i - 4] + y_values[i - 3] + y_values[i - 2] + y_values[i - 1] + y_values[i]) / 5
            else:
                y_value = None
            yDMA5.append(y_value)




        # DMA3 method
        yDMA3 = []
        for i in range(len(y_values)):
            if i >= 2:
                y_value = (y_values[i - 2] + y_values[i - 1] + y_values[i]) / 3
            else:
                y_value = None
            yDMA3.append(y_value)

        yEnsemble = []
        for i in range(len(y_values)):
            y_value = []
            if  str(yDMA3[i]).isnumeric() == True :
                y_value.append(yDMA3[i])
            if  str(yDMA5[i]).isnumeric() == True :
                y_value.append(yDMA5[i])
            y_value.append(ySavGol[i])
            y_value.append(ySpline[i])
            ensembleitem = statistics.median(y_value)
            yEnsemble.append(ensembleitem)

        # METRICS
        MaxValueY = max(NDVIvalue)
        MetricsSavGol=[]
        MetricsSpline=[]
        MetricsDMA3=[]
        MetricsDMA5=[]
        MetricsEnsemble=[]
        name = []
        colors = []
        legendlist=[]


        ##PLOT DATA

        if self.dlg.cbSavotskyGolay.isChecked() == True:
            dxdy = np.diff(np.array(ySavGol)) / np.diff(np.array(x_new))
            indexEOS = self.EOSFinder(dxdy)
            indexSOS = self.SOSFinder(dxdy)
            AMP = MaxValueY - ySavGol[indexSOS]
            DUR = x_new[indexEOS]-x_new[indexSOS]
            name.append('Savotsky Golay')
            MetricsSavGol.append(round(AMP,5))
            MetricsSavGol.append(DUR)
            MetricsSavGol.append(DATA2[indexSOS])
            MetricsSavGol.append(DATA2[indexEOS])
            legendlist.append(MetricsSavGol)

            colors.append('olive')
            plt.plot_date(DATA2, ySavGol, '-', color='olive')


        if self.dlg.cbSpline.isChecked() == True:
            dxdy = np.diff(np.array(ySpline)) / np.diff(np.array(x_new))
            indexEOS = self.EOSFinder(dxdy)
            indexSOS = self.SOSFinder(dxdy)
            AMP = MaxValueY - ySpline[indexSOS]
            DUR = x_new[indexEOS]-x_new[indexSOS]
            name.append('Spline')
            MetricsSpline.append(round(AMP,5))
            MetricsSpline.append(DUR)
            MetricsSpline.append(DATA2[indexSOS])
            MetricsSpline.append(DATA2[indexEOS])
            legendlist.append(MetricsSpline)
            colors.append('Gold')
            plt.plot_date(DATA2, ySpline, '-', color='gold')

        if self.dlg.cbDMA3.isChecked() == True:
            dxdy = np.diff(np.array(yDMA3[2:])) / np.diff(np.array(x_new[2:]))
            indexEOS = self.EOSFinder(dxdy)+2
            indexSOS = self.SOSFinder(dxdy)+2
            AMP = MaxValueY - yDMA3[indexSOS]
            DUR = x_new[indexEOS] - x_new[indexSOS]
            name.append('DMA3')
            MetricsDMA3.append(round(AMP,5))
            MetricsDMA3.append(DUR)
            MetricsDMA3.append(DATA2[indexSOS])
            MetricsDMA3.append(DATA2[indexEOS])
            legendlist.append(MetricsDMA3)
            colors.append('Mediumseagreen')
            plt.plot_date(DATA2, yDMA3, '-', color='Mediumseagreen')

        if self.dlg.cbDMA5.isChecked() == True:
            dxdy = np.diff(np.array(yDMA5[4:])) / np.diff(np.array(x_new[4:]))
            indexEOS = self.EOSFinder(dxdy)+4
            indexSOS = self.SOSFinder(dxdy)+4
            AMP = MaxValueY - yDMA5[indexSOS]
            DUR = x_new[indexEOS]-x_new[indexSOS]
            name.append('DMA5')
            MetricsDMA5.append(round(AMP,5))
            MetricsDMA5.append(DUR)
            MetricsDMA5.append(DATA2[indexSOS])
            MetricsDMA5.append(DATA2[indexEOS])
            legendlist.append(MetricsDMA5)
            colors.append('Steelblue')
            plt.plot_date(DATA2, yDMA5, '-', color='Steelblue')

        if self.dlg.cbEnsemble.isChecked() == True:

            dxdy = np.diff(np.array(yEnsemble)) / np.diff(np.array(x_new))
            indexEOS=self.EOSFinder(dxdy)
            indexSOS=self.SOSFinder(dxdy)

            AMP = MaxValueY - yEnsemble[indexSOS]
            DUR = x_new[indexEOS]-x_new[indexSOS]
            name.append('Ensemble')
            MetricsEnsemble.append(round(AMP,5))
            MetricsEnsemble.append(DUR)
            MetricsEnsemble.append(DATA2[indexSOS])
            MetricsEnsemble.append(DATA2[indexEOS])
            legendlist.append(MetricsEnsemble)
            colors.append('darkorange')
            plt.plot_date(DATA2, yEnsemble, '-', color='darkorange')



        #ADD Points
        plt.plot_date(DATA2, NDVIvalue, 'o', color='royalblue')
        legendinformetion = ['Amplitude', 'Duration', 'SOS', 'EOS', 'SOSN']

        # X label as date


        #SHOW
        table = ax.table(cellText=legendlist,
                         rowLabels=name,
                         rowColours=colors,
                         colLabels=legendinformetion,
                         loc='bottom',
                         bbox = [0.0, -0.45, 1, .28])

        table.scale(1, 2)
        table.set_fontsize(12)
        fig.subplots_adjust(bottom=0.3, left=0.3)
        plt.show()

    def selectfolderpath(self):

        self.pathtofolder = QFileDialog.getExistingDirectory(self.dlg, 'Select Folder')
        self.dlg.pathtofolder.setText(str(self.pathtofolder))

    def selectshppath(self):

        pathtoshp_total = str(QFileDialog.getOpenFileName(self.dlg, 'Select File'))
        pathtoshp_list = pathtoshp_total.split(",")
        self.pathtoshp = str(pathtoshp_list[0])[2:-1]
        self.dlg.pathtoshp.setText(str(self.pathtoshp))

    def SOSFinder(self,YD):
        SOSfind = 0
        counterreg = 0
        counter = 0
        for i in range(len(YD)):
            if counter == 0:
                SOScounter = i
            if i < len(YD) - 2 and i > 0:
                if YD[i + 1] > 0 or YD[i + 1] > YD[i - 1]:
                    counter = counter + 1
                else:
                    if counter > counterreg:
                        counterreg = counter
                        counter = 0
                        SOSfind = SOScounter

            SOS = int(SOSfind)

        return SOS

    def EOSFinder(self,YD):
        EOSfind = 0
        counter = 0
        for i in range(len(YD)):
            if i > 0 and i < len(YD) - 1:
                if YD[i - 1] < 0 or YD[i - 2] > YD[i]:
                    counter = counter + 1
                    if counter > 0 and YD[i + 1] > YD[i]:
                        counter = 0
                        EOSfind = i + 1

            EOS = int(EOSfind)

        return EOS